import type { Lead, Quote, DashboardStats } from "./types";

// ─── Mock Leads ──────────────────────────────────────────────────────────────
export const mockLeads: Lead[] = [
  {
    id: "lead-001",
    created_at: "2026-04-28T09:14:00Z",
    updated_at: "2026-04-28T14:22:00Z",
    name: "Marcus Reynolds",
    email: "marcus.reynolds@gmail.com",
    phone: "+1 (480) 555-0192",
    company: undefined,
    service_type: "automotive",
    message: "I have a 1969 Ferrari Dino 246 GT and a 2021 Lamborghini Huracán. Looking for full engine bay and exterior detail using dry ice. Can you accommodate both in one visit?",
    source: "contact_form",
    status: "new",
    priority: "high",
    notes: undefined,
    assigned_to: undefined,
    follow_up_date: "2026-04-30T09:00:00Z",
    quote_id: undefined,
  },
  {
    id: "lead-002",
    created_at: "2026-04-27T16:45:00Z",
    updated_at: "2026-04-28T10:00:00Z",
    name: "Capt. James Thornton",
    email: "j.thornton@bluewater-yachts.com",
    phone: "+1 (954) 555-0347",
    company: "Bluewater Yachts LLC",
    service_type: "marine",
    message: "78-foot sportfish, bilge and engine room haven't been properly cleaned in 6 years. Docked at Bahia Mar Marina, Fort Lauderdale. Need full dockside service ASAP.",
    source: "contact_form",
    status: "contacted",
    priority: "high",
    notes: "Called 4/27. Very interested. Wants quote by Friday. Boat is available Mon-Wed next week.",
    assigned_to: "Anthony T.",
    follow_up_date: "2026-05-01T10:00:00Z",
    quote_id: "quote-001",
  },
  {
    id: "lead-003",
    created_at: "2026-04-26T11:30:00Z",
    updated_at: "2026-04-27T09:15:00Z",
    name: "Dr. Alicia Moreno",
    email: "a.moreno@pharmalogix.com",
    phone: "+1 (813) 555-0581",
    company: "PharmaLogix Tampa",
    service_type: "industrial",
    message: "We operate a pharmaceutical cold-chain facility under FDA oversight. Need quarterly sanitation cleaning that meets our protocols. Looking for a long-term service contract.",
    source: "contact_form",
    status: "qualified",
    priority: "high",
    notes: "Sent capability deck 4/26. Scheduled site visit for 5/3. High-value contract opportunity — estimated $48k/yr.",
    assigned_to: "Anthony T.",
    follow_up_date: "2026-05-03T09:00:00Z",
    quote_id: "quote-002",
  },
  {
    id: "lead-004",
    created_at: "2026-04-25T14:20:00Z",
    updated_at: "2026-04-26T08:00:00Z",
    name: "Derek Fontaine",
    email: "derek@fontainecollection.com",
    phone: "+1 (305) 555-0723",
    company: "Fontaine Collection",
    service_type: "automotive",
    message: "Private collector with 14 vehicles including several pre-war Bugattis. Looking for a trusted dry ice specialist for annual deep clean of the entire collection.",
    source: "referral",
    status: "qualified",
    priority: "high",
    notes: "Referred by Marcus Reynolds. Extremely high-value client. Prefers weekend appointments. Collection stored in climate-controlled facility in Coral Gables.",
    assigned_to: "Anthony T.",
    follow_up_date: "2026-05-02T14:00:00Z",
    quote_id: undefined,
  },
  {
    id: "lead-005",
    created_at: "2026-04-24T09:55:00Z",
    updated_at: "2026-04-25T11:30:00Z",
    name: "Sandra Kowalski",
    email: "sandra.k@gmail.com",
    phone: "+1 (727) 555-0144",
    company: undefined,
    service_type: "automotive",
    message: "2019 Porsche 911 GT3 RS. Engine bay cleaning and full exterior. Located in St. Pete.",
    source: "quote_widget",
    status: "contacted",
    priority: "medium",
    notes: "Sent quote 4/25. Waiting on response.",
    assigned_to: "Anthony T.",
    follow_up_date: "2026-04-29T10:00:00Z",
    quote_id: "quote-003",
  },
  {
    id: "lead-006",
    created_at: "2026-04-22T13:10:00Z",
    updated_at: "2026-04-24T09:00:00Z",
    name: "Gulf Coast Logistics",
    email: "ops@gulfcoastlogistics.com",
    phone: "+1 (813) 555-0962",
    company: "Gulf Coast Logistics Inc.",
    service_type: "industrial",
    message: "Refrigerated warehouse facility — 40,000 sq ft. Need annual deep clean of evaporator coils and cold storage units. Looking for certified vendor.",
    source: "direct",
    status: "new",
    priority: "medium",
    notes: undefined,
    assigned_to: undefined,
    follow_up_date: "2026-04-30T09:00:00Z",
    quote_id: undefined,
  },
  {
    id: "lead-007",
    created_at: "2026-04-20T10:00:00Z",
    updated_at: "2026-04-22T15:00:00Z",
    name: "Tyler Breckenridge",
    email: "tyler@breckenridgemotors.com",
    phone: "+1 (561) 555-0388",
    company: "Breckenridge Motors",
    service_type: "automotive",
    message: "Exotic car dealership. Looking for a recurring service partner for pre-sale detailing using dry ice. Typically 4-6 vehicles per month.",
    source: "referral",
    status: "qualified",
    priority: "medium",
    notes: "Recurring B2B opportunity. Wants monthly retainer pricing. Sent proposal 4/22.",
    assigned_to: "Anthony T.",
    follow_up_date: "2026-05-01T10:00:00Z",
    quote_id: "quote-004",
  },
  {
    id: "lead-008",
    created_at: "2026-04-18T08:30:00Z",
    updated_at: "2026-04-21T14:00:00Z",
    name: "Marina Bay Club",
    email: "manager@marinabayclub.com",
    phone: "+1 (941) 555-0215",
    company: "Marina Bay Club",
    service_type: "marine",
    message: "We have 12 club-owned vessels ranging from 32 to 65 feet. Looking for seasonal cleaning contract.",
    source: "direct",
    status: "lost",
    priority: "medium",
    notes: "Went with a competitor on price. May revisit in Q4.",
    assigned_to: "Anthony T.",
    follow_up_date: undefined,
    quote_id: undefined,
  },
];

// ─── Mock Quotes ─────────────────────────────────────────────────────────────
export const mockQuotes: Quote[] = [
  {
    id: "quote-001",
    created_at: "2026-04-27T18:00:00Z",
    updated_at: "2026-04-28T09:00:00Z",
    quote_number: "DJS-2026-0041",
    lead_id: "lead-002",
    client_name: "Capt. James Thornton",
    client_email: "j.thornton@bluewater-yachts.com",
    client_phone: "+1 (954) 555-0347",
    client_company: "Bluewater Yachts LLC",
    service_type: "marine",
    asset_description: "78-foot sportfish — bilge, engine room, hull running gear",
    location: "Bahia Mar Marina, Fort Lauderdale, FL",
    scheduled_date: "2026-05-05T08:00:00Z",
    line_items: [
      { id: "li-001", description: "Engine room dry ice blast (full)", quantity: 1, unit_price: 2800, total: 2800 },
      { id: "li-002", description: "Bilge cleaning — 78ft vessel", quantity: 1, unit_price: 1200, total: 1200 },
      { id: "li-003", description: "Hull running gear & props", quantity: 1, unit_price: 950, total: 950 },
      { id: "li-004", description: "Travel & dockside setup fee", quantity: 1, unit_price: 350, total: 350 },
    ],
    subtotal: 5300,
    tax: 371,
    total: 5671,
    currency: "USD",
    status: "sent",
    valid_until: "2026-05-11T23:59:00Z",
    internal_notes: "High-value client. Prioritize scheduling.",
    client_notes: "All work performed dockside. No haul-out required. Estimated 6-8 hours.",
  },
  {
    id: "quote-002",
    created_at: "2026-04-26T14:00:00Z",
    updated_at: "2026-04-27T10:00:00Z",
    quote_number: "DJS-2026-0040",
    lead_id: "lead-003",
    client_name: "Dr. Alicia Moreno",
    client_email: "a.moreno@pharmalogix.com",
    client_phone: "+1 (813) 555-0581",
    client_company: "PharmaLogix Tampa",
    service_type: "industrial",
    asset_description: "Pharmaceutical cold-chain facility — quarterly sanitation",
    location: "PharmaLogix Tampa, 4800 N Dale Mabry Hwy, Tampa, FL",
    scheduled_date: "2026-05-10T07:00:00Z",
    line_items: [
      { id: "li-005", description: "Cold storage unit sanitation (per unit × 8)", quantity: 8, unit_price: 1400, total: 11200 },
      { id: "li-006", description: "Evaporator coil cleaning (per unit × 4)", quantity: 4, unit_price: 800, total: 3200 },
      { id: "li-007", description: "Compliance documentation package", quantity: 1, unit_price: 600, total: 600 },
      { id: "li-008", description: "Annual contract discount (10%)", quantity: 1, unit_price: -1500, total: -1500 },
    ],
    subtotal: 13500,
    tax: 945,
    total: 14445,
    currency: "USD",
    status: "approved",
    valid_until: "2026-05-15T23:59:00Z",
    internal_notes: "Annual contract — 4 visits/year. Total contract value ~$57,780.",
    client_notes: "Includes FDA-compliant documentation and technician certification on file.",
  },
  {
    id: "quote-003",
    created_at: "2026-04-25T12:00:00Z",
    updated_at: "2026-04-25T12:00:00Z",
    quote_number: "DJS-2026-0039",
    lead_id: "lead-005",
    client_name: "Sandra Kowalski",
    client_email: "sandra.k@gmail.com",
    client_phone: "+1 (727) 555-0144",
    client_company: undefined,
    service_type: "automotive",
    asset_description: "2019 Porsche 911 GT3 RS — engine bay + full exterior",
    location: "Client residence, St. Petersburg, FL",
    scheduled_date: undefined,
    line_items: [
      { id: "li-009", description: "Engine bay dry ice blast", quantity: 1, unit_price: 650, total: 650 },
      { id: "li-010", description: "Full exterior panel cleaning", quantity: 1, unit_price: 450, total: 450 },
      { id: "li-011", description: "Mobile service fee", quantity: 1, unit_price: 150, total: 150 },
    ],
    subtotal: 1250,
    tax: 87.50,
    total: 1337.50,
    currency: "USD",
    status: "pending",
    valid_until: "2026-05-09T23:59:00Z",
    internal_notes: "",
    client_notes: "Mobile service — we come to you. Estimated 3 hours.",
  },
  {
    id: "quote-004",
    created_at: "2026-04-22T16:00:00Z",
    updated_at: "2026-04-23T09:00:00Z",
    quote_number: "DJS-2026-0038",
    lead_id: "lead-007",
    client_name: "Tyler Breckenridge",
    client_email: "tyler@breckenridgemotors.com",
    client_phone: "+1 (561) 555-0388",
    client_company: "Breckenridge Motors",
    service_type: "automotive",
    asset_description: "Monthly retainer — 4-6 exotic vehicles pre-sale detail",
    location: "Breckenridge Motors, West Palm Beach, FL",
    scheduled_date: "2026-05-01T09:00:00Z",
    line_items: [
      { id: "li-012", description: "Monthly retainer — up to 6 vehicles", quantity: 1, unit_price: 3600, total: 3600 },
      { id: "li-013", description: "Additional vehicle (over 6)", quantity: 0, unit_price: 650, total: 0 },
      { id: "li-014", description: "Travel & setup (monthly)", quantity: 1, unit_price: 200, total: 200 },
    ],
    subtotal: 3800,
    tax: 266,
    total: 4066,
    currency: "USD",
    status: "sent",
    valid_until: "2026-05-06T23:59:00Z",
    internal_notes: "B2B retainer. If approved, set up recurring invoice.",
    client_notes: "Monthly service. Scheduling flexible around your inventory.",
  },
  {
    id: "quote-005",
    created_at: "2026-04-15T10:00:00Z",
    updated_at: "2026-04-20T14:00:00Z",
    quote_number: "DJS-2026-0035",
    lead_id: undefined,
    client_name: "Harbour Isle Marina",
    client_email: "service@harbourisle.com",
    client_phone: "+1 (941) 555-0099",
    client_company: "Harbour Isle Marina",
    service_type: "marine",
    asset_description: "Spring cleaning — 6 marina-owned vessels 32-45ft",
    location: "Harbour Isle Marina, Anna Maria Island, FL",
    scheduled_date: "2026-04-22T07:00:00Z",
    line_items: [
      { id: "li-015", description: "Engine room blast — 32-45ft (per vessel × 6)", quantity: 6, unit_price: 1400, total: 8400 },
      { id: "li-016", description: "Bilge cleaning (per vessel × 6)", quantity: 6, unit_price: 600, total: 3600 },
      { id: "li-017", description: "Fleet discount (15%)", quantity: 1, unit_price: -1800, total: -1800 },
    ],
    subtotal: 10200,
    tax: 714,
    total: 10914,
    currency: "USD",
    status: "completed",
    valid_until: "2026-04-25T23:59:00Z",
    internal_notes: "Completed 4/22. Invoice paid 4/24. Great client — follow up for fall contract.",
    client_notes: "",
  },
];

// ─── Dashboard Stats ──────────────────────────────────────────────────────────
export const mockStats: DashboardStats = {
  total_leads: mockLeads.length,
  new_leads: mockLeads.filter(l => l.status === "new").length,
  leads_this_week: 5,
  leads_change_pct: 25,
  total_quotes: mockQuotes.length,
  pending_quotes: mockQuotes.filter(q => q.status === "pending" || q.status === "sent").length,
  approved_quotes: mockQuotes.filter(q => q.status === "approved").length,
  total_revenue: mockQuotes.filter(q => q.status === "completed" || q.status === "approved").reduce((s, q) => s + q.total, 0),
  revenue_this_month: 25359,
  revenue_change_pct: 18,
  conversion_rate: 62,
};

// ─── Chart Data ───────────────────────────────────────────────────────────────
export const leadsOverTime = [
  { month: "Nov", leads: 4, quotes: 2 },
  { month: "Dec", leads: 6, quotes: 4 },
  { month: "Jan", leads: 9, quotes: 6 },
  { month: "Feb", leads: 7, quotes: 5 },
  { month: "Mar", leads: 12, quotes: 8 },
  { month: "Apr", leads: 8, quotes: 5 },
];

export const revenueOverTime = [
  { month: "Nov", revenue: 8400 },
  { month: "Dec", revenue: 12200 },
  { month: "Jan", revenue: 9800 },
  { month: "Feb", revenue: 15600 },
  { month: "Mar", revenue: 21400 },
  { month: "Apr", revenue: 25359 },
];

export const serviceBreakdown = [
  { name: "Automotive", value: 45, color: "#9ED8FF" },
  { name: "Marine", value: 35, color: "#CFAE6E" },
  { name: "Industrial", value: 20, color: "#74C7FF" },
];
